//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int AdminKey { get; set; }
        public Nullable<int> OrganizationKey { get; set; }
        public Nullable<bool> GlobalConsultant { get; set; }
        public bool GlobalByCompany { get; set; }
        public Nullable<int> ConsultantKey { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Access { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool ViewReports { get; set; }
        public string ReportOrgs { get; set; }
    }
}
