//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCertificationRegistration
    {
        public int CertificationRegistrationKey { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string Name { get; set; }
        public string Organization { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string BasicDates { get; set; }
        public string WorkPlace360Date { get; set; }
        public string TeambuildingDate { get; set; }
        public string CoachingDate { get; set; }
        public string SelectionDate { get; set; }
        public bool OnlineVersion { get; set; }
        public string HeardAbout { get; set; }
        public bool Removed { get; set; }
    }
}
