//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountryCode
    {
        public short CountryCodeKey { get; set; }
        public string Country { get; set; }
        public string A2 { get; set; }
        public string A3 { get; set; }
        public short Number { get; set; }
    }
}
