//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboard_Product
    {
        public short ProductKey { get; set; }
        public short CategoryKey { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LongDescription { get; set; }
        public short WeightPounds { get; set; }
        public short WeightOunces { get; set; }
        public bool NoShipping { get; set; }
        public bool Active { get; set; }
        public bool Removed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public short ModifiedBy { get; set; }
    }
}
