//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboard_TransactionUnitDetail
    {
        public int TransactionUnitDetailKey { get; set; }
        public int TransactionUnitKey { get; set; }
        public string Description { get; set; }
        public bool People { get; set; }
        public bool Segments { get; set; }
        public bool Competencies { get; set; }
        public bool Other { get; set; }
    }
}
