//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboard_Banner
    {
        public int BannerKey { get; set; }
        public string Image { get; set; }
        public bool Active { get; set; }
        public bool Removed { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
