//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboard_OrderItem
    {
        public int OrderItemKey { get; set; }
        public int OrderKey { get; set; }
        public bool IsAssessment { get; set; }
        public int ProjectKey { get; set; }
        public int ProductKey { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public decimal SubTotal { get; set; }
        public string Description { get; set; }
        public bool IsAddition { get; set; }
        public bool IsPerson { get; set; }
        public bool IsReport { get; set; }
        public string Name { get; set; }
        public string Weight { get; set; }
    
        public virtual tblDashboard_Order tblDashboard_Order { get; set; }
    }
}
