//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboard_ProductPrice
    {
        public short ProductPriceKey { get; set; }
        public short ProductKey { get; set; }
        public short UserType { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DateCreated { get; set; }
        public short ModifiedBy { get; set; }
    }
}
