//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboard_OrderProject
    {
        public int OrderProjectKey { get; set; }
        public int OrderKey { get; set; }
        public int ProjectKey { get; set; }
    }
}
