//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_Company
    {
        public tblMaster_Company()
        {
            this.tblMaster_Organization = new HashSet<tblMaster_Organization>();
        }
    
        public int CompanyKey { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<tblMaster_Organization> tblMaster_Organization { get; set; }
    }
}
