//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_User
    {
        public tblMaster_User()
        {
            this.tblMaster_Project = new HashSet<tblMaster_Project>();
        }
    
        public int UserKey { get; set; }
        public Nullable<int> OrganizationKey { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsConsultant { get; set; }
        public Nullable<bool> IsWebservice { get; set; }
        public Nullable<bool> WebserviceReports { get; set; }
        public Nullable<bool> WebserviceScores { get; set; }
        public Nullable<bool> WebserviceShortForm { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedByKey { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserName { get; set; }
        public string UserTitle { get; set; }
        public string UserFax { get; set; }
        public string UserAddress { get; set; }
        public string UserAddressCont { get; set; }
        public string UserCity { get; set; }
        public string UserState { get; set; }
        public string UserZip { get; set; }
        public string UserCountry { get; set; }
        public string UserWebsite { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserDegree { get; set; }
        public string UserYear { get; set; }
        public string UserInstitution { get; set; }
        public string UserMajor { get; set; }
        public string UserRelevantCourses { get; set; }
        public string UserRelevantWorkshops { get; set; }
        public string UserExperience { get; set; }
        public string UserProfessional { get; set; }
        public string UserStudent { get; set; }
        public bool CCOnFile { get; set; }
        public bool Invoice { get; set; }
        public bool Removed { get; set; }
        public string Experience360 { get; set; }
        public string Student360 { get; set; }
        public bool IsWorkplace { get; set; }
        public bool Is360 { get; set; }
        public int UserType { get; set; }
        public bool GlobalConsultant { get; set; }
        public int MasterTrainerCompanyKey { get; set; }
        public bool MasterTrainerMap { get; set; }
        public bool GlobalByCompany { get; set; }
    
        public virtual tblMaster_Organization tblMaster_Organization { get; set; }
        public virtual ICollection<tblMaster_Project> tblMaster_Project { get; set; }
    }
}
