//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster360_Template
    {
        public int TemplateKey { get; set; }
        public int OrganizationKey { get; set; }
        public string TemplateData { get; set; }
        public bool IsPublic { get; set; }
        public bool Archived { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
