//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_UserData
    {
        public int UserDataKey { get; set; }
        public Nullable<int> UserKey { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UserTitle { get; set; }
        public Nullable<int> UserCompany { get; set; }
        public string UserOrganization { get; set; }
        public string UserFax { get; set; }
        public string UserAddress { get; set; }
        public string UserAddressCont { get; set; }
        public string UserCity { get; set; }
        public string UserState { get; set; }
        public string UserZip { get; set; }
        public string UserCountry { get; set; }
        public string UserWebsite { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserDegree { get; set; }
        public string UserYear { get; set; }
        public string UserInstitution { get; set; }
        public string UserMajor { get; set; }
        public string UserRelevantCourses { get; set; }
        public string UserRelevantWorkshops { get; set; }
        public string UserExperience { get; set; }
        public string UserProfessional { get; set; }
        public string UserStudent { get; set; }
        public Nullable<bool> UserSendSchoolPlaceToQT { get; set; }
        public Nullable<bool> UserSendWorkplaceToQT { get; set; }
        public Nullable<System.DateTime> UserCreatedDate { get; set; }
        public Nullable<bool> UserApprove { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public Nullable<bool> Removed { get; set; }
        public string UserType { get; set; }
        public string AccountCode { get; set; }
        public Nullable<bool> CCOnFile { get; set; }
        public Nullable<bool> Invoice { get; set; }
    }
}
