//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_Project_m2m_Questionnaire
    {
        public int Project_Questionnaire_Key { get; set; }
        public Nullable<int> OldWebserviceID { get; set; }
        public Nullable<int> ProjectKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public Nullable<int> Questionnaire_LanguageKey { get; set; }
        public Nullable<int> Report_LanguageKey { get; set; }
        public Nullable<int> NormGroupKey { get; set; }
        public Nullable<bool> Teamer { get; set; }
        public Nullable<bool> Leader { get; set; }
        public Nullable<bool> CareerGuider { get; set; }
        public Nullable<bool> Learner { get; set; }
        public string ReportGUID { get; set; }
        public string TraitReportName { get; set; }
        public string NarratorReportName { get; set; }
        public string ConsultantReportName { get; set; }
        public string CapacitorReportName { get; set; }
        public string TraitNarratorReportName { get; set; }
        public string LeaderReportName { get; set; }
        public string CareerGuiderReportName { get; set; }
        public string ValuesReportName { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<bool> SRDone { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tblMaster_Project tblMaster_Project { get; set; }
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
