//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_Project_m2m_Competency
    {
        public int ProjectCompetencyKey { get; set; }
        public Nullable<int> ProjectKey { get; set; }
        public Nullable<int> CompetencyKey { get; set; }
    }
}
