//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_Product
    {
        public tblMaster_Product()
        {
            this.tblMaster_Project = new HashSet<tblMaster_Project>();
            this.tblMaster_QuestionnaireType = new HashSet<tblMaster_QuestionnaireType>();
        }
    
        public int ProductKey { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<tblMaster_Project> tblMaster_Project { get; set; }
        public virtual ICollection<tblMaster_QuestionnaireType> tblMaster_QuestionnaireType { get; set; }
    }
}
