//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster360_Anchor
    {
        public tblMaster360_Anchor()
        {
            this.tblMaster360_Anchor_m2m_Organization = new HashSet<tblMaster360_Anchor_m2m_Organization>();
        }
    
        public int AnchorKey { get; set; }
        public string LeftAnchor { get; set; }
        public string RightAnchor { get; set; }
        public bool IsPublic { get; set; }
        public bool Approved { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<tblMaster360_Anchor_m2m_Organization> tblMaster360_Anchor_m2m_Organization { get; set; }
    }
}
