//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_Competency
    {
        public tblMaster_Competency()
        {
            this.tblMaster_Competency_m2m_CompetencyGroup = new HashSet<tblMaster_Competency_m2m_CompetencyGroup>();
            this.tblMaster_CompetencyType_m2m_Competency = new HashSet<tblMaster_CompetencyType_m2m_Competency>();
        }
    
        public int CompetencyKey { get; set; }
        public string CompetencyName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<tblMaster_Competency_m2m_CompetencyGroup> tblMaster_Competency_m2m_CompetencyGroup { get; set; }
        public virtual ICollection<tblMaster_CompetencyType_m2m_Competency> tblMaster_CompetencyType_m2m_Competency { get; set; }
    }
}
