//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster360_Rater
    {
        public tblMaster360_Rater()
        {
            this.tblProject360_Rater = new HashSet<tblProject360_Rater>();
        }
    
        public int RaterKey { get; set; }
        public int OrganizationKey { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public bool Archived { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual tblMaster_Organization tblMaster_Organization { get; set; }
        public virtual ICollection<tblProject360_Rater> tblProject360_Rater { get; set; }
    }
}
