//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_CompetencyGroup
    {
        public tblMaster_CompetencyGroup()
        {
            this.tblMaster_Competency_m2m_CompetencyGroup = new HashSet<tblMaster_Competency_m2m_CompetencyGroup>();
            this.tblMaster_Project = new HashSet<tblMaster_Project>();
        }
    
        public int CompetencyGroupKey { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> OrganizationKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<tblMaster_Competency_m2m_CompetencyGroup> tblMaster_Competency_m2m_CompetencyGroup { get; set; }
        public virtual ICollection<tblMaster_Project> tblMaster_Project { get; set; }
    }
}
