//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_Organization
    {
        public tblMaster_Organization()
        {
            this.tblMaster_User = new HashSet<tblMaster_User>();
            this.tblMaster360_Anchor_m2m_Organization = new HashSet<tblMaster360_Anchor_m2m_Organization>();
            this.tblMaster360_Competency_m2m_Organization = new HashSet<tblMaster360_Competency_m2m_Organization>();
            this.tblMaster360_QuestionnaireItem_m2m_Organization = new HashSet<tblMaster360_QuestionnaireItem_m2m_Organization>();
            this.tblMaster360_Rater = new HashSet<tblMaster360_Rater>();
            this.tblMaster360_RaterCategory_m2m_Organization = new HashSet<tblMaster360_RaterCategory_m2m_Organization>();
        }
    
        public int OrganizationKey { get; set; }
        public Nullable<int> CompanyKey { get; set; }
        public Nullable<int> CompetencyTypeKey { get; set; }
        public string OrgName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<bool> IsCoBranded { get; set; }
        public string WebLogo { get; set; }
        public string WebURL { get; set; }
        public string WebFooterBranding { get; set; }
        public string WebMessage { get; set; }
        public string ReportLogo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool TaxExempt { get; set; }
    
        public virtual tblMaster_Company tblMaster_Company { get; set; }
        public virtual ICollection<tblMaster_User> tblMaster_User { get; set; }
        public virtual ICollection<tblMaster360_Anchor_m2m_Organization> tblMaster360_Anchor_m2m_Organization { get; set; }
        public virtual ICollection<tblMaster360_Competency_m2m_Organization> tblMaster360_Competency_m2m_Organization { get; set; }
        public virtual ICollection<tblMaster360_QuestionnaireItem_m2m_Organization> tblMaster360_QuestionnaireItem_m2m_Organization { get; set; }
        public virtual ICollection<tblMaster360_Rater> tblMaster360_Rater { get; set; }
        public virtual ICollection<tblMaster360_RaterCategory_m2m_Organization> tblMaster360_RaterCategory_m2m_Organization { get; set; }
    }
}
