//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster360_QuestionnaireItem
    {
        public tblMaster360_QuestionnaireItem()
        {
            this.tblMaster360_QuestionnaireItem_m2m_Organization = new HashSet<tblMaster360_QuestionnaireItem_m2m_Organization>();
        }
    
        public int QuestionnaireItemKey { get; set; }
        public int CompetencyKey { get; set; }
        public string ItemText { get; set; }
        public bool IsPublic { get; set; }
        public bool Archived { get; set; }
        public bool Approved { get; set; }
        public string Mean { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual tblMaster360_Competency tblMaster360_Competency { get; set; }
        public virtual ICollection<tblMaster360_QuestionnaireItem_m2m_Organization> tblMaster360_QuestionnaireItem_m2m_Organization { get; set; }
    }
}
