//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_Questionnaire
    {
        public tblMaster_Questionnaire()
        {
            this.tblMaster_Project_m2m_Questionnaire = new HashSet<tblMaster_Project_m2m_Questionnaire>();
            this.tblSchoolplace_AnswersConverted = new HashSet<tblSchoolplace_AnswersConverted>();
            this.tblSchoolplace_AnswersDemographics = new HashSet<tblSchoolplace_AnswersDemographics>();
            this.tblSchoolplace_AnswersInverted = new HashSet<tblSchoolplace_AnswersInverted>();
            this.tblSchoolplace_AnswersOriginal = new HashSet<tblSchoolplace_AnswersOriginal>();
            this.tblSchoolplace_AnswersRaw = new HashSet<tblSchoolplace_AnswersRaw>();
            this.tblSchoolplace_AnswersStandard = new HashSet<tblSchoolplace_AnswersStandard>();
            this.tblSchoolplace_AnswersStandardInverted = new HashSet<tblSchoolplace_AnswersStandardInverted>();
            this.tblSchoolplace_AnswersStandardOptimized = new HashSet<tblSchoolplace_AnswersStandardOptimized>();
            this.tblValues_AnswersConverted = new HashSet<tblValues_AnswersConverted>();
            this.tblValues_AnswersDemographics = new HashSet<tblValues_AnswersDemographics>();
            this.tblValues_AnswersInverted = new HashSet<tblValues_AnswersInverted>();
            this.tblValues_AnswersOriginal = new HashSet<tblValues_AnswersOriginal>();
            this.tblValues_AnswersPolarity = new HashSet<tblValues_AnswersPolarity>();
            this.tblValues_AnswersRaw = new HashSet<tblValues_AnswersRaw>();
            this.tblValues_AnswersStandard = new HashSet<tblValues_AnswersStandard>();
            this.tblWorkplace_AnswersConverted = new HashSet<tblWorkplace_AnswersConverted>();
            this.tblWorkplace_AnswersDemographics = new HashSet<tblWorkplace_AnswersDemographics>();
            this.tblWorkplace_AnswersInverted = new HashSet<tblWorkplace_AnswersInverted>();
            this.tblWorkplace_AnswersOriginal = new HashSet<tblWorkplace_AnswersOriginal>();
            this.tblWorkplace_AnswersRaw = new HashSet<tblWorkplace_AnswersRaw>();
            this.tblWorkplace_AnswersStandard = new HashSet<tblWorkplace_AnswersStandard>();
            this.tblWorkplace_AnswersStandardInverted = new HashSet<tblWorkplace_AnswersStandardInverted>();
            this.tblWorkplace_AnswersStandardOptimized = new HashSet<tblWorkplace_AnswersStandardOptimized>();
        }
    
        public int QuestionnaireKey { get; set; }
        public Nullable<int> OldQuestionnaireID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsStarted { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsCareerGuiderStarted { get; set; }
        public Nullable<bool> IsCareerGuiderCompleted { get; set; }
        public Nullable<bool> IsQuestionnaireSent { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateCareerGuiderStarted { get; set; }
        public Nullable<System.DateTime> DateCareerGuiderCompleted { get; set; }
        public Nullable<System.DateTime> DateQuestionnaireSent { get; set; }
        public Nullable<System.DateTime> DateLastQuestionnaireSent { get; set; }
        public Nullable<System.DateTime> DateLastVisited { get; set; }
        public string BirthDate { get; set; }
        public string WebserviceTrackingKey { get; set; }
        public int ResearchSet { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedByKey { get; set; }
    
        public virtual ICollection<tblMaster_Project_m2m_Questionnaire> tblMaster_Project_m2m_Questionnaire { get; set; }
        public virtual ICollection<tblSchoolplace_AnswersConverted> tblSchoolplace_AnswersConverted { get; set; }
        public virtual ICollection<tblSchoolplace_AnswersDemographics> tblSchoolplace_AnswersDemographics { get; set; }
        public virtual ICollection<tblSchoolplace_AnswersInverted> tblSchoolplace_AnswersInverted { get; set; }
        public virtual ICollection<tblSchoolplace_AnswersOriginal> tblSchoolplace_AnswersOriginal { get; set; }
        public virtual ICollection<tblSchoolplace_AnswersRaw> tblSchoolplace_AnswersRaw { get; set; }
        public virtual ICollection<tblSchoolplace_AnswersStandard> tblSchoolplace_AnswersStandard { get; set; }
        public virtual ICollection<tblSchoolplace_AnswersStandardInverted> tblSchoolplace_AnswersStandardInverted { get; set; }
        public virtual ICollection<tblSchoolplace_AnswersStandardOptimized> tblSchoolplace_AnswersStandardOptimized { get; set; }
        public virtual ICollection<tblValues_AnswersConverted> tblValues_AnswersConverted { get; set; }
        public virtual ICollection<tblValues_AnswersDemographics> tblValues_AnswersDemographics { get; set; }
        public virtual ICollection<tblValues_AnswersInverted> tblValues_AnswersInverted { get; set; }
        public virtual ICollection<tblValues_AnswersOriginal> tblValues_AnswersOriginal { get; set; }
        public virtual ICollection<tblValues_AnswersPolarity> tblValues_AnswersPolarity { get; set; }
        public virtual ICollection<tblValues_AnswersRaw> tblValues_AnswersRaw { get; set; }
        public virtual ICollection<tblValues_AnswersStandard> tblValues_AnswersStandard { get; set; }
        public virtual ICollection<tblWorkplace_AnswersConverted> tblWorkplace_AnswersConverted { get; set; }
        public virtual ICollection<tblWorkplace_AnswersDemographics> tblWorkplace_AnswersDemographics { get; set; }
        public virtual ICollection<tblWorkplace_AnswersInverted> tblWorkplace_AnswersInverted { get; set; }
        public virtual ICollection<tblWorkplace_AnswersOriginal> tblWorkplace_AnswersOriginal { get; set; }
        public virtual ICollection<tblWorkplace_AnswersRaw> tblWorkplace_AnswersRaw { get; set; }
        public virtual ICollection<tblWorkplace_AnswersStandard> tblWorkplace_AnswersStandard { get; set; }
        public virtual ICollection<tblWorkplace_AnswersStandardInverted> tblWorkplace_AnswersStandardInverted { get; set; }
        public virtual ICollection<tblWorkplace_AnswersStandardOptimized> tblWorkplace_AnswersStandardOptimized { get; set; }
    }
}
