//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster360_QuestionnaireText
    {
        public int QuestionnaireTextKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string Rater { get; set; }
        public string Assessee { get; set; }
        public string DevelopedBy { get; set; }
        public string InstructionTitle { get; set; }
        public string Instructions { get; set; }
        public string ExampleTitle { get; set; }
        public string Example1 { get; set; }
        public string Example1Detail { get; set; }
        public string Example2 { get; set; }
        public string Example2Detail { get; set; }
        public string Example3 { get; set; }
        public string Example3Detail { get; set; }
        public string TrueText { get; set; }
        public string FalseText { get; set; }
        public string MoreInstructions { get; set; }
        public string ImportanceIntro { get; set; }
        public string SubmitButton { get; set; }
        public string SaveButton { get; set; }
        public string AboutButton { get; set; }
        public string HelpButton { get; set; }
        public string FooterText { get; set; }
        public string ErrorText { get; set; }
        public string AgreementImage { get; set; }
        public string AgreementImageText { get; set; }
        public string AgreementText { get; set; }
        public string AgreementButton { get; set; }
        public string AgreementLoadingText { get; set; }
        public string SavingText { get; set; }
        public string OtherText { get; set; }
        public string CompleteText { get; set; }
        public string SaveText { get; set; }
        public string LoginError { get; set; }
        public string CommentInstructions { get; set; }
        public string Comments1Text { get; set; }
        public string Comments2Text { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
