//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster360_Competency
    {
        public tblMaster360_Competency()
        {
            this.tblMaster360_Competency_m2m_Organization = new HashSet<tblMaster360_Competency_m2m_Organization>();
            this.tblMaster360_QuestionnaireItem = new HashSet<tblMaster360_QuestionnaireItem>();
        }
    
        public int CompetencyKey { get; set; }
        public string Name { get; set; }
        public bool IsPublic { get; set; }
        public bool Approved { get; set; }
        public string Mean { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<tblMaster360_Competency_m2m_Organization> tblMaster360_Competency_m2m_Organization { get; set; }
        public virtual ICollection<tblMaster360_QuestionnaireItem> tblMaster360_QuestionnaireItem { get; set; }
    }
}
