//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject360_Approval
    {
        public int ApprovalKey { get; set; }
        public int ProjectKey { get; set; }
        public int OrganizationKey { get; set; }
        public string Competencies { get; set; }
        public string Items { get; set; }
        public int AnchorKey { get; set; }
        public int ProjectApproved { get; set; }
        public string ReasonDisapproved { get; set; }
        public int ApprovedBy { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
