//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject360_Rater
    {
        public tblProject360_Rater()
        {
            this.tblProject360_RaterResponse = new HashSet<tblProject360_RaterResponse>();
        }
    
        public int ProjectRaterKey { get; set; }
        public int ProjectKey { get; set; }
        public int GroupNumber { get; set; }
        public int RaterKey { get; set; }
        public bool IsAssessee { get; set; }
        public bool IsBilled { get; set; }
        public string RaterCategory { get; set; }
        public int CategoryType { get; set; }
        public int QuestionnaireLanguageKey { get; set; }
        public int ReportLanguageKey { get; set; }
        public string WP360ReportName { get; set; }
        public bool IsStarted { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsQuestionnaireSent { get; set; }
        public System.DateTime DateStarted { get; set; }
        public System.DateTime DateCompleted { get; set; }
        public System.DateTime DateQuestionnaireSent { get; set; }
        public System.DateTime DateLastQuestionnaireSent { get; set; }
        public System.DateTime DateLastVisited { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ModifiedByKey { get; set; }
    
        public virtual tblMaster_Project tblMaster_Project { get; set; }
        public virtual tblMaster360_Rater tblMaster360_Rater { get; set; }
        public virtual ICollection<tblProject360_RaterResponse> tblProject360_RaterResponse { get; set; }
    }
}
