//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolplace_AnswersStandardOptimized
    {
        public int Schoolplace_AnswersStandardOptimizedKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<double> nq { get; set; }
        public Nullable<double> eq { get; set; }
        public Nullable<double> oq { get; set; }
        public Nullable<double> aq { get; set; }
        public Nullable<double> cq { get; set; }
        public Nullable<double> n1q { get; set; }
        public Nullable<double> n2q { get; set; }
        public Nullable<double> n3q { get; set; }
        public Nullable<double> n4q { get; set; }
        public Nullable<double> e1q { get; set; }
        public Nullable<double> e2q { get; set; }
        public Nullable<double> e3q { get; set; }
        public Nullable<double> e4q { get; set; }
        public Nullable<double> e5q { get; set; }
        public Nullable<double> e6q { get; set; }
        public Nullable<double> o1q { get; set; }
        public Nullable<double> o2q { get; set; }
        public Nullable<double> o3q { get; set; }
        public Nullable<double> o4q { get; set; }
        public Nullable<double> a1q { get; set; }
        public Nullable<double> a2q { get; set; }
        public Nullable<double> a3q { get; set; }
        public Nullable<double> a4q { get; set; }
        public Nullable<double> a5q { get; set; }
        public Nullable<double> c1q { get; set; }
        public Nullable<double> c2q { get; set; }
        public Nullable<double> c3q { get; set; }
        public Nullable<double> c4q { get; set; }
        public Nullable<double> c5q { get; set; }
    
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
