//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolplace_LanguageCoverTOC
    {
        public int LanguageCoverTOCKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string CustomizedReport { get; set; }
        public string DOBString { get; set; }
        public string DateString { get; set; }
        public string DateFormat { get; set; }
        public string TOC { get; set; }
        public string ReportTitle { get; set; }
        public string ReportSubtitle { get; set; }
        public string FiveSupertraits { get; set; }
        public string N { get; set; }
        public string E { get; set; }
        public string O { get; set; }
        public string A { get; set; }
        public string C { get; set; }
        public string Composite { get; set; }
        public string CompositeText { get; set; }
        public string Page { get; set; }
        public string Rights { get; set; }
        public string Contact { get; set; }
        public string SpecialReportsString { get; set; }
    }
}
