//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolplace_AnswersDemographics
    {
        public int Schoolplace_AnswersDemographicsKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public string Gender { get; set; }
        public Nullable<short> Age { get; set; }
        public string Ethnicity { get; set; }
        public string FavoriteSubject { get; set; }
        public string School { get; set; }
        public string City { get; set; }
        public string StateCountry { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
