//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolplace_AnswersStandard
    {
        public int Schoolplace_AnswersStandardKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<double> n { get; set; }
        public Nullable<double> e { get; set; }
        public Nullable<double> o { get; set; }
        public Nullable<double> a { get; set; }
        public Nullable<double> c { get; set; }
        public Nullable<double> n1 { get; set; }
        public Nullable<double> n2 { get; set; }
        public Nullable<double> n3 { get; set; }
        public Nullable<double> n4 { get; set; }
        public Nullable<double> e1 { get; set; }
        public Nullable<double> e2 { get; set; }
        public Nullable<double> e3 { get; set; }
        public Nullable<double> e4 { get; set; }
        public Nullable<double> e5 { get; set; }
        public Nullable<double> e6 { get; set; }
        public Nullable<double> o1 { get; set; }
        public Nullable<double> o2 { get; set; }
        public Nullable<double> o3 { get; set; }
        public Nullable<double> o4 { get; set; }
        public Nullable<double> a1 { get; set; }
        public Nullable<double> a2 { get; set; }
        public Nullable<double> a3 { get; set; }
        public Nullable<double> a4 { get; set; }
        public Nullable<double> a5 { get; set; }
        public Nullable<double> c1 { get; set; }
        public Nullable<double> c2 { get; set; }
        public Nullable<double> c3 { get; set; }
        public Nullable<double> c4 { get; set; }
        public Nullable<double> c5 { get; set; }
    
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
