//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_QuestionDemographicDetail
    {
        public int ValuesDemographicDetailKey { get; set; }
        public Nullable<int> ValuesDemographicKey { get; set; }
        public string ResponseENG { get; set; }
        public string ResponseISPN { get; set; }
        public string ResponseGER { get; set; }
        public string ResponsePTG { get; set; }
        public string ResponseCN { get; set; }
        public string ResponseFIN { get; set; }
        public string ResponseJA { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> OtherTextBox { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tblValues_QuestionDemographic tblValues_QuestionDemographic { get; set; }
    }
}
