//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_LanguageHeaderFooter
    {
        public int HeaderFooterKey { get; set; }
        public int LanguageKey { get; set; }
        public string CustomizedReportText { get; set; }
        public string ValuesReportText { get; set; }
        public string DateText { get; set; }
        public string NormGroupText { get; set; }
        public string PageText { get; set; }
        public string RightsText { get; set; }
    }
}
