//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_LanguageTOCSubtitles
    {
        public int TOCSubtitlesKey { get; set; }
        public int TOCTitlesKey { get; set; }
        public short TOCEnum { get; set; }
        public string SubtitleText { get; set; }
        public short Rank { get; set; }
    }
}
