//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_LanguageValuesBalanceInterpretation
    {
        public int ValuesBalanceIntepretKey { get; set; }
        public short LanguageKey { get; set; }
        public short ValuesBalanceEnum { get; set; }
        public string Text { get; set; }
    }
}
