//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_LanguageIntroMain
    {
        public int IntroMainKey { get; set; }
        public short LanguageKey { get; set; }
        public string HeadingText { get; set; }
        public string ParagraphText { get; set; }
        public short Rank { get; set; }
    }
}
