//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_LanguageBriefDefinition
    {
        public int BriefDefinitionKey { get; set; }
        public short LanguageKey { get; set; }
        public short ValuesEnum { get; set; }
        public string Definition { get; set; }
        public string Motto { get; set; }
    }
}
