//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_QuestionDemographic
    {
        public tblValues_QuestionDemographic()
        {
            this.tblValues_QuestionDemographicDetail = new HashSet<tblValues_QuestionDemographicDetail>();
        }
    
        public int ValuesDemographicKey { get; set; }
        public string QuestionENG { get; set; }
        public string QuestionISPN { get; set; }
        public string QuestionGER { get; set; }
        public string QuestionPTG { get; set; }
        public string QuestionCN { get; set; }
        public string QuestionFIN { get; set; }
        public string QuestionJA { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> IsPostBack { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<tblValues_QuestionDemographicDetail> tblValues_QuestionDemographicDetail { get; set; }
    }
}
