//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_AnswersRaw
    {
        public int Values_AnswersRawKey { get; set; }
        public int QuestionnaireKey { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Achievement { get; set; }
        public int Activity { get; set; }
        public int Beauty { get; set; }
        public int Competition { get; set; }
        public int Justice { get; set; }
        public int Health { get; set; }
        public int Helping { get; set; }
        public int Independence { get; set; }
        public int Intellect { get; set; }
        public int Materialism { get; set; }
        public int Pleasure { get; set; }
        public int Power { get; set; }
        public int Relationships { get; set; }
        public int Spirituality { get; set; }
        public int Stability { get; set; }
        public int Status { get; set; }
    
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
