//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_LanguageAgencyCommunion
    {
        public int AgencyCommKey { get; set; }
        public short LanguageKey { get; set; }
        public string HeaderText { get; set; }
        public string SubHeaderText { get; set; }
        public string TopParagraphText { get; set; }
        public string BottomParagraphText { get; set; }
        public string InterpretationText { get; set; }
    }
}
