//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValues_LanguageValuesInLife
    {
        public int ValuesInLifeKey { get; set; }
        public short LanguageKey { get; set; }
        public string LegendText { get; set; }
        public string NoteText { get; set; }
        public string IntroParagraph { get; set; }
        public string NoteParagraph { get; set; }
    }
}
