//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageNarratorPartTwoValues
    {
        public int ValuesKey { get; set; }
        public short Enumerator { get; set; }
        public short LanguageKey { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
