//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_AnswersInverted
    {
        public int Workplace_AnswersInvertedKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> q1i { get; set; }
        public Nullable<int> q2i { get; set; }
        public Nullable<int> q3i { get; set; }
        public Nullable<int> q4i { get; set; }
        public Nullable<int> q5i { get; set; }
        public Nullable<int> q6i { get; set; }
        public Nullable<int> q7i { get; set; }
        public Nullable<int> q8i { get; set; }
        public Nullable<int> q9i { get; set; }
        public Nullable<int> q10i { get; set; }
        public Nullable<int> q11i { get; set; }
        public Nullable<int> q12i { get; set; }
        public Nullable<int> q13i { get; set; }
        public Nullable<int> q14i { get; set; }
        public Nullable<int> q15i { get; set; }
        public Nullable<int> q16i { get; set; }
        public Nullable<int> q17i { get; set; }
        public Nullable<int> q18i { get; set; }
        public Nullable<int> q19i { get; set; }
        public Nullable<int> q20i { get; set; }
        public Nullable<int> q21i { get; set; }
        public Nullable<int> q22i { get; set; }
        public Nullable<int> q23i { get; set; }
        public Nullable<int> q24i { get; set; }
        public Nullable<int> q25i { get; set; }
        public Nullable<int> q26i { get; set; }
        public Nullable<int> q27i { get; set; }
        public Nullable<int> q28i { get; set; }
        public Nullable<int> q29i { get; set; }
        public Nullable<int> q30i { get; set; }
        public Nullable<int> q31i { get; set; }
        public Nullable<int> q32i { get; set; }
        public Nullable<int> q33i { get; set; }
        public Nullable<int> q34i { get; set; }
        public Nullable<int> q35i { get; set; }
        public Nullable<int> q36i { get; set; }
        public Nullable<int> q37i { get; set; }
        public Nullable<int> q38i { get; set; }
        public Nullable<int> q39i { get; set; }
        public Nullable<int> q40i { get; set; }
        public Nullable<int> q41i { get; set; }
        public Nullable<int> q42i { get; set; }
        public Nullable<int> q43i { get; set; }
        public Nullable<int> q44i { get; set; }
        public Nullable<int> q45i { get; set; }
        public Nullable<int> q46i { get; set; }
        public Nullable<int> q47i { get; set; }
        public Nullable<int> q48i { get; set; }
        public Nullable<int> q49i { get; set; }
        public Nullable<int> q50i { get; set; }
        public Nullable<int> q51i { get; set; }
        public Nullable<int> q52i { get; set; }
        public Nullable<int> q53i { get; set; }
        public Nullable<int> q54i { get; set; }
        public Nullable<int> q55i { get; set; }
        public Nullable<int> q56i { get; set; }
        public Nullable<int> q57i { get; set; }
        public Nullable<int> q58i { get; set; }
        public Nullable<int> q59i { get; set; }
        public Nullable<int> q60i { get; set; }
        public Nullable<int> q61i { get; set; }
        public Nullable<int> q62i { get; set; }
        public Nullable<int> q63i { get; set; }
        public Nullable<int> q64i { get; set; }
        public Nullable<int> q65i { get; set; }
        public Nullable<int> q66i { get; set; }
        public Nullable<int> q67i { get; set; }
        public Nullable<int> q68i { get; set; }
        public Nullable<int> q69i { get; set; }
        public Nullable<int> q70i { get; set; }
        public Nullable<int> q71i { get; set; }
        public Nullable<int> q72i { get; set; }
        public Nullable<int> q73i { get; set; }
        public Nullable<int> q74i { get; set; }
        public Nullable<int> q75i { get; set; }
        public Nullable<int> q76i { get; set; }
        public Nullable<int> q77i { get; set; }
        public Nullable<int> q78i { get; set; }
        public Nullable<int> q79i { get; set; }
        public Nullable<int> q80i { get; set; }
        public Nullable<int> q81i { get; set; }
        public Nullable<int> q82i { get; set; }
        public Nullable<int> q83i { get; set; }
        public Nullable<int> q84i { get; set; }
        public Nullable<int> q85i { get; set; }
        public Nullable<int> q86i { get; set; }
        public Nullable<int> q87i { get; set; }
        public Nullable<int> q88i { get; set; }
        public Nullable<int> q89i { get; set; }
        public Nullable<int> q90i { get; set; }
        public Nullable<int> q91i { get; set; }
        public Nullable<int> q92i { get; set; }
        public Nullable<int> q93i { get; set; }
        public Nullable<int> q94i { get; set; }
        public Nullable<int> q95i { get; set; }
        public Nullable<int> q96i { get; set; }
        public Nullable<int> q97i { get; set; }
        public Nullable<int> q98i { get; set; }
        public Nullable<int> q99i { get; set; }
        public Nullable<int> q100i { get; set; }
        public Nullable<int> q101i { get; set; }
        public Nullable<int> q102i { get; set; }
        public Nullable<int> q103i { get; set; }
        public Nullable<int> q104i { get; set; }
        public Nullable<int> q105i { get; set; }
        public Nullable<int> q106i { get; set; }
        public Nullable<int> q107i { get; set; }
        public Nullable<int> q108i { get; set; }
        public Nullable<int> q109i { get; set; }
        public Nullable<int> q110i { get; set; }
        public Nullable<int> q111i { get; set; }
        public Nullable<int> q112i { get; set; }
        public Nullable<int> q113i { get; set; }
        public Nullable<int> q114i { get; set; }
        public Nullable<int> q115i { get; set; }
        public Nullable<int> q116i { get; set; }
        public Nullable<int> q117i { get; set; }
        public Nullable<int> q118i { get; set; }
        public Nullable<int> q119i { get; set; }
        public Nullable<int> q120i { get; set; }
        public Nullable<int> q121i { get; set; }
        public Nullable<int> q122i { get; set; }
        public Nullable<int> q123i { get; set; }
        public Nullable<int> q124i { get; set; }
        public Nullable<int> q125i { get; set; }
        public Nullable<int> q126i { get; set; }
        public Nullable<int> q127i { get; set; }
        public Nullable<int> q128i { get; set; }
        public Nullable<int> q129i { get; set; }
        public Nullable<int> q130i { get; set; }
        public Nullable<int> q131i { get; set; }
        public Nullable<int> q132i { get; set; }
        public Nullable<int> q133i { get; set; }
        public Nullable<int> q134i { get; set; }
        public Nullable<int> q135i { get; set; }
        public Nullable<int> q136i { get; set; }
        public Nullable<int> q137i { get; set; }
        public Nullable<int> q138i { get; set; }
        public Nullable<int> q139i { get; set; }
        public Nullable<int> q140i { get; set; }
        public Nullable<int> q141i { get; set; }
        public Nullable<int> q142i { get; set; }
        public Nullable<int> q143i { get; set; }
    
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
