//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageCapacitorIntro
    {
        public int LanguageCapacitorKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string DevelopedBy { get; set; }
        public string SummaryHeader { get; set; }
        public string SummaryText { get; set; }
        public string ReportDescHeader { get; set; }
        public string ReportDescText { get; set; }
        public string CompetencySubHeader { get; set; }
        public string CompetencyHeader { get; set; }
        public string ImportantNote { get; set; }
        public string ImportantNoteText { get; set; }
    }
}
