//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_AnswersOriginal
    {
        public int Workplace_AnswersOriginalKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> q1o { get; set; }
        public Nullable<int> q2o { get; set; }
        public Nullable<int> q3o { get; set; }
        public Nullable<int> q4o { get; set; }
        public Nullable<int> q5o { get; set; }
        public Nullable<int> q6o { get; set; }
        public Nullable<int> q7o { get; set; }
        public Nullable<int> q8o { get; set; }
        public Nullable<int> q9o { get; set; }
        public Nullable<int> q10o { get; set; }
        public Nullable<int> q11o { get; set; }
        public Nullable<int> q12o { get; set; }
        public Nullable<int> q13o { get; set; }
        public Nullable<int> q14o { get; set; }
        public Nullable<int> q15o { get; set; }
        public Nullable<int> q16o { get; set; }
        public Nullable<int> q17o { get; set; }
        public Nullable<int> q18o { get; set; }
        public Nullable<int> q19o { get; set; }
        public Nullable<int> q20o { get; set; }
        public Nullable<int> q21o { get; set; }
        public Nullable<int> q22o { get; set; }
        public Nullable<int> q23o { get; set; }
        public Nullable<int> q24o { get; set; }
        public Nullable<int> q25o { get; set; }
        public Nullable<int> q26o { get; set; }
        public Nullable<int> q27o { get; set; }
        public Nullable<int> q28o { get; set; }
        public Nullable<int> q29o { get; set; }
        public Nullable<int> q30o { get; set; }
        public Nullable<int> q31o { get; set; }
        public Nullable<int> q32o { get; set; }
        public Nullable<int> q33o { get; set; }
        public Nullable<int> q34o { get; set; }
        public Nullable<int> q35o { get; set; }
        public Nullable<int> q36o { get; set; }
        public Nullable<int> q37o { get; set; }
        public Nullable<int> q38o { get; set; }
        public Nullable<int> q39o { get; set; }
        public Nullable<int> q40o { get; set; }
        public Nullable<int> q41o { get; set; }
        public Nullable<int> q42o { get; set; }
        public Nullable<int> q43o { get; set; }
        public Nullable<int> q44o { get; set; }
        public Nullable<int> q45o { get; set; }
        public Nullable<int> q46o { get; set; }
        public Nullable<int> q47o { get; set; }
        public Nullable<int> q48o { get; set; }
        public Nullable<int> q49o { get; set; }
        public Nullable<int> q50o { get; set; }
        public Nullable<int> q51o { get; set; }
        public Nullable<int> q52o { get; set; }
        public Nullable<int> q53o { get; set; }
        public Nullable<int> q54o { get; set; }
        public Nullable<int> q55o { get; set; }
        public Nullable<int> q56o { get; set; }
        public Nullable<int> q57o { get; set; }
        public Nullable<int> q58o { get; set; }
        public Nullable<int> q59o { get; set; }
        public Nullable<int> q60o { get; set; }
        public Nullable<int> q61o { get; set; }
        public Nullable<int> q62o { get; set; }
        public Nullable<int> q63o { get; set; }
        public Nullable<int> q64o { get; set; }
        public Nullable<int> q65o { get; set; }
        public Nullable<int> q66o { get; set; }
        public Nullable<int> q67o { get; set; }
        public Nullable<int> q68o { get; set; }
        public Nullable<int> q69o { get; set; }
        public Nullable<int> q70o { get; set; }
        public Nullable<int> q71o { get; set; }
        public Nullable<int> q72o { get; set; }
        public Nullable<int> q73o { get; set; }
        public Nullable<int> q74o { get; set; }
        public Nullable<int> q75o { get; set; }
        public Nullable<int> q76o { get; set; }
        public Nullable<int> q77o { get; set; }
        public Nullable<int> q78o { get; set; }
        public Nullable<int> q79o { get; set; }
        public Nullable<int> q80o { get; set; }
        public Nullable<int> q81o { get; set; }
        public Nullable<int> q82o { get; set; }
        public Nullable<int> q83o { get; set; }
        public Nullable<int> q84o { get; set; }
        public Nullable<int> q85o { get; set; }
        public Nullable<int> q86o { get; set; }
        public Nullable<int> q87o { get; set; }
        public Nullable<int> q88o { get; set; }
        public Nullable<int> q89o { get; set; }
        public Nullable<int> q90o { get; set; }
        public Nullable<int> q91o { get; set; }
        public Nullable<int> q92o { get; set; }
        public Nullable<int> q93o { get; set; }
        public Nullable<int> q94o { get; set; }
        public Nullable<int> q95o { get; set; }
        public Nullable<int> q96o { get; set; }
        public Nullable<int> q97o { get; set; }
        public Nullable<int> q98o { get; set; }
        public Nullable<int> q99o { get; set; }
        public Nullable<int> q100o { get; set; }
        public Nullable<int> q101o { get; set; }
        public Nullable<int> q102o { get; set; }
        public Nullable<int> q103o { get; set; }
        public Nullable<int> q104o { get; set; }
        public Nullable<int> q105o { get; set; }
        public Nullable<int> q106o { get; set; }
        public Nullable<int> q107o { get; set; }
        public Nullable<int> q108o { get; set; }
        public Nullable<int> q109o { get; set; }
        public Nullable<int> q110o { get; set; }
        public Nullable<int> q111o { get; set; }
        public Nullable<int> q112o { get; set; }
        public Nullable<int> q113o { get; set; }
        public Nullable<int> q114o { get; set; }
        public Nullable<int> q115o { get; set; }
        public Nullable<int> q116o { get; set; }
        public Nullable<int> q117o { get; set; }
        public Nullable<int> q118o { get; set; }
        public Nullable<int> q119o { get; set; }
        public Nullable<int> q120o { get; set; }
        public Nullable<int> q121o { get; set; }
        public Nullable<int> q122o { get; set; }
        public Nullable<int> q123o { get; set; }
        public Nullable<int> q124o { get; set; }
        public Nullable<int> q125o { get; set; }
        public Nullable<int> q126o { get; set; }
        public Nullable<int> q127o { get; set; }
        public Nullable<int> q128o { get; set; }
        public Nullable<int> q129o { get; set; }
        public Nullable<int> q130o { get; set; }
        public Nullable<int> q131o { get; set; }
        public Nullable<int> q132o { get; set; }
        public Nullable<int> q133o { get; set; }
        public Nullable<int> q134o { get; set; }
        public Nullable<int> q135o { get; set; }
        public Nullable<int> q136o { get; set; }
        public Nullable<int> q137o { get; set; }
        public Nullable<int> q138o { get; set; }
        public Nullable<int> q139o { get; set; }
        public Nullable<int> q140o { get; set; }
        public Nullable<int> q141o { get; set; }
        public Nullable<int> q142o { get; set; }
        public Nullable<int> q143o { get; set; }
    
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
