//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_AnswersRaw
    {
        public int Workplace_AnswersRawKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> nr { get; set; }
        public Nullable<int> er { get; set; }
        public Nullable<int> or { get; set; }
        public Nullable<int> ar { get; set; }
        public Nullable<int> csr { get; set; }
        public Nullable<int> n1r { get; set; }
        public Nullable<int> n2r { get; set; }
        public Nullable<int> n3r { get; set; }
        public Nullable<int> n4r { get; set; }
        public Nullable<int> e1r { get; set; }
        public Nullable<int> e2r { get; set; }
        public Nullable<int> e3r { get; set; }
        public Nullable<int> e4r { get; set; }
        public Nullable<int> e5r { get; set; }
        public Nullable<int> e6r { get; set; }
        public Nullable<int> o1r { get; set; }
        public Nullable<int> o2r { get; set; }
        public Nullable<int> o3r { get; set; }
        public Nullable<int> o4r { get; set; }
        public Nullable<int> a1r { get; set; }
        public Nullable<int> a2r { get; set; }
        public Nullable<int> a3r { get; set; }
        public Nullable<int> a4r { get; set; }
        public Nullable<int> c1r { get; set; }
        public Nullable<int> c2r { get; set; }
        public Nullable<int> c3r { get; set; }
        public Nullable<int> c4r { get; set; }
        public Nullable<int> c5r { get; set; }
    
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
