//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageConsultantTOC
    {
        public int ConsultantTOCKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string ReportTitle { get; set; }
        public string Introduction { get; set; }
        public string IndivTraitScores { get; set; }
        public string ResponseBias { get; set; }
        public string ItemResponses { get; set; }
        public string TraitBlends { get; set; }
        public string TraitSummary { get; set; }
        public string Page { get; set; }
        public string Rights { get; set; }
    }
}
