//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageConsultantBlend
    {
        public int ConsultantBlendKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public Nullable<int> BlendEnum { get; set; }
        public string Blend { get; set; }
        public string EnglishName { get; set; }
        public string EnglishDefinition { get; set; }
        public string SpanishName { get; set; }
        public string SpanishDefinition { get; set; }
        public string GermanName { get; set; }
        public string GermanDefinition { get; set; }
        public string ChineseName { get; set; }
        public string ChineseDefinition { get; set; }
        public string PortugueseName { get; set; }
        public string PortugueseDefinition { get; set; }
    }
}
