//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageConsultantBlendText
    {
        public int ConsultantBlendTextKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string ReportHeader { get; set; }
        public string InterpretGuide { get; set; }
        public string Note { get; set; }
        public string NoteText { get; set; }
        public string NameHeader { get; set; }
        public string BlendsHeader { get; set; }
        public string DefinitionHeader { get; set; }
    }
}
