//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_AnswersConverted
    {
        public int Workplace_AnswersConvertedKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> q1 { get; set; }
        public Nullable<int> q2 { get; set; }
        public Nullable<int> q3 { get; set; }
        public Nullable<int> q4 { get; set; }
        public Nullable<int> q5 { get; set; }
        public Nullable<int> q6 { get; set; }
        public Nullable<int> q7 { get; set; }
        public Nullable<int> q8 { get; set; }
        public Nullable<int> q9 { get; set; }
        public Nullable<int> q10 { get; set; }
        public Nullable<int> q11 { get; set; }
        public Nullable<int> q12 { get; set; }
        public Nullable<int> q13 { get; set; }
        public Nullable<int> q14 { get; set; }
        public Nullable<int> q15 { get; set; }
        public Nullable<int> q16 { get; set; }
        public Nullable<int> q17 { get; set; }
        public Nullable<int> q18 { get; set; }
        public Nullable<int> q19 { get; set; }
        public Nullable<int> q20 { get; set; }
        public Nullable<int> q21 { get; set; }
        public Nullable<int> q22 { get; set; }
        public Nullable<int> q23 { get; set; }
        public Nullable<int> q24 { get; set; }
        public Nullable<int> q25 { get; set; }
        public Nullable<int> q26 { get; set; }
        public Nullable<int> q27 { get; set; }
        public Nullable<int> q28 { get; set; }
        public Nullable<int> q29 { get; set; }
        public Nullable<int> q30 { get; set; }
        public Nullable<int> q31 { get; set; }
        public Nullable<int> q32 { get; set; }
        public Nullable<int> q33 { get; set; }
        public Nullable<int> q34 { get; set; }
        public Nullable<int> q35 { get; set; }
        public Nullable<int> q36 { get; set; }
        public Nullable<int> q37 { get; set; }
        public Nullable<int> q38 { get; set; }
        public Nullable<int> q39 { get; set; }
        public Nullable<int> q40 { get; set; }
        public Nullable<int> q41 { get; set; }
        public Nullable<int> q42 { get; set; }
        public Nullable<int> q43 { get; set; }
        public Nullable<int> q44 { get; set; }
        public Nullable<int> q45 { get; set; }
        public Nullable<int> q46 { get; set; }
        public Nullable<int> q47 { get; set; }
        public Nullable<int> q48 { get; set; }
        public Nullable<int> q49 { get; set; }
        public Nullable<int> q50 { get; set; }
        public Nullable<int> q51 { get; set; }
        public Nullable<int> q52 { get; set; }
        public Nullable<int> q53 { get; set; }
        public Nullable<int> q54 { get; set; }
        public Nullable<int> q55 { get; set; }
        public Nullable<int> q56 { get; set; }
        public Nullable<int> q57 { get; set; }
        public Nullable<int> q58 { get; set; }
        public Nullable<int> q59 { get; set; }
        public Nullable<int> q60 { get; set; }
        public Nullable<int> q61 { get; set; }
        public Nullable<int> q62 { get; set; }
        public Nullable<int> q63 { get; set; }
        public Nullable<int> q64 { get; set; }
        public Nullable<int> q65 { get; set; }
        public Nullable<int> q66 { get; set; }
        public Nullable<int> q67 { get; set; }
        public Nullable<int> q68 { get; set; }
        public Nullable<int> q69 { get; set; }
        public Nullable<int> q70 { get; set; }
        public Nullable<int> q71 { get; set; }
        public Nullable<int> q72 { get; set; }
        public Nullable<int> q73 { get; set; }
        public Nullable<int> q74 { get; set; }
        public Nullable<int> q75 { get; set; }
        public Nullable<int> q76 { get; set; }
        public Nullable<int> q77 { get; set; }
        public Nullable<int> q78 { get; set; }
        public Nullable<int> q79 { get; set; }
        public Nullable<int> q80 { get; set; }
        public Nullable<int> q81 { get; set; }
        public Nullable<int> q82 { get; set; }
        public Nullable<int> q83 { get; set; }
        public Nullable<int> q84 { get; set; }
        public Nullable<int> q85 { get; set; }
        public Nullable<int> q86 { get; set; }
        public Nullable<int> q87 { get; set; }
        public Nullable<int> q88 { get; set; }
        public Nullable<int> q89 { get; set; }
        public Nullable<int> q90 { get; set; }
        public Nullable<int> q91 { get; set; }
        public Nullable<int> q92 { get; set; }
        public Nullable<int> q93 { get; set; }
        public Nullable<int> q94 { get; set; }
        public Nullable<int> q95 { get; set; }
        public Nullable<int> q96 { get; set; }
        public Nullable<int> q97 { get; set; }
        public Nullable<int> q98 { get; set; }
        public Nullable<int> q99 { get; set; }
        public Nullable<int> q100 { get; set; }
        public Nullable<int> q101 { get; set; }
        public Nullable<int> q102 { get; set; }
        public Nullable<int> q103 { get; set; }
        public Nullable<int> q104 { get; set; }
        public Nullable<int> q105 { get; set; }
        public Nullable<int> q106 { get; set; }
        public Nullable<int> q107 { get; set; }
        public Nullable<int> q108 { get; set; }
        public Nullable<int> q109 { get; set; }
        public Nullable<int> q110 { get; set; }
        public Nullable<int> q111 { get; set; }
        public Nullable<int> q112 { get; set; }
        public Nullable<int> q113 { get; set; }
        public Nullable<int> q114 { get; set; }
        public Nullable<int> q115 { get; set; }
        public Nullable<int> q116 { get; set; }
        public Nullable<int> q117 { get; set; }
        public Nullable<int> q118 { get; set; }
        public Nullable<int> q119 { get; set; }
        public Nullable<int> q120 { get; set; }
        public Nullable<int> q121 { get; set; }
        public Nullable<int> q122 { get; set; }
        public Nullable<int> q123 { get; set; }
        public Nullable<int> q124 { get; set; }
        public Nullable<int> q125 { get; set; }
        public Nullable<int> q126 { get; set; }
        public Nullable<int> q127 { get; set; }
        public Nullable<int> q128 { get; set; }
        public Nullable<int> q129 { get; set; }
        public Nullable<int> q130 { get; set; }
        public Nullable<int> q131 { get; set; }
        public Nullable<int> q132 { get; set; }
        public Nullable<int> q133 { get; set; }
        public Nullable<int> q134 { get; set; }
        public Nullable<int> q135 { get; set; }
        public Nullable<int> q136 { get; set; }
        public Nullable<int> q137 { get; set; }
        public Nullable<int> q138 { get; set; }
        public Nullable<int> q139 { get; set; }
        public Nullable<int> q140 { get; set; }
        public Nullable<int> q141 { get; set; }
        public Nullable<int> q142 { get; set; }
        public Nullable<int> q143 { get; set; }
    
        public virtual tblMaster_Questionnaire tblMaster_Questionnaire { get; set; }
    }
}
