//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LeaderModule
    {
        public int WorkplaceLeaderModuleKey { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
