//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageCapacitorText
    {
        public int Workplace_CapacitorTextKey { get; set; }
        public Nullable<int> CompetencyKey { get; set; }
        public string Trait { get; set; }
        public Nullable<int> TraitEnergy { get; set; }
        public string EnglishText { get; set; }
        public string SpanishText { get; set; }
        public string GermanText { get; set; }
        public string ChineseText { get; set; }
    }
}
