//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_AnswersOriginalResearch
    {
        public int Workplace_AnswersOriginalResearchKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> r1 { get; set; }
        public Nullable<int> r2 { get; set; }
        public Nullable<int> r3 { get; set; }
        public Nullable<int> r4 { get; set; }
        public Nullable<int> r5 { get; set; }
        public Nullable<int> r6 { get; set; }
        public Nullable<int> r7 { get; set; }
        public Nullable<int> r8 { get; set; }
        public Nullable<int> r9 { get; set; }
        public Nullable<int> r10 { get; set; }
        public Nullable<int> r11 { get; set; }
        public Nullable<int> r12 { get; set; }
        public Nullable<int> r13 { get; set; }
        public Nullable<int> r14 { get; set; }
        public Nullable<int> r15 { get; set; }
        public Nullable<int> r16 { get; set; }
        public Nullable<int> r17 { get; set; }
        public Nullable<int> r18 { get; set; }
        public Nullable<int> r19 { get; set; }
        public Nullable<int> r20 { get; set; }
        public Nullable<int> r21 { get; set; }
        public Nullable<int> r22 { get; set; }
        public Nullable<int> r23 { get; set; }
        public Nullable<int> r24 { get; set; }
        public Nullable<int> r25 { get; set; }
        public Nullable<int> r26 { get; set; }
        public Nullable<int> r27 { get; set; }
        public Nullable<int> r28 { get; set; }
        public Nullable<int> r29 { get; set; }
        public Nullable<int> r30 { get; set; }
        public Nullable<int> r31 { get; set; }
        public Nullable<int> r32 { get; set; }
        public Nullable<int> r33 { get; set; }
        public Nullable<int> r34 { get; set; }
        public Nullable<int> r35 { get; set; }
        public Nullable<int> r36 { get; set; }
        public Nullable<int> r37 { get; set; }
        public Nullable<int> r38 { get; set; }
        public Nullable<int> r39 { get; set; }
        public Nullable<int> r40 { get; set; }
        public Nullable<int> r41 { get; set; }
        public Nullable<int> r42 { get; set; }
        public Nullable<int> r43 { get; set; }
        public Nullable<int> r44 { get; set; }
        public Nullable<int> r45 { get; set; }
        public Nullable<int> r46 { get; set; }
        public Nullable<int> r47 { get; set; }
        public Nullable<int> r48 { get; set; }
        public Nullable<int> r49 { get; set; }
        public Nullable<int> r50 { get; set; }
        public Nullable<int> r51 { get; set; }
        public Nullable<int> r52 { get; set; }
        public Nullable<int> r53 { get; set; }
        public Nullable<int> r54 { get; set; }
        public Nullable<int> r55 { get; set; }
        public Nullable<int> r56 { get; set; }
        public Nullable<int> r57 { get; set; }
        public Nullable<int> r58 { get; set; }
        public Nullable<int> r59 { get; set; }
        public Nullable<int> r60 { get; set; }
        public Nullable<int> r61 { get; set; }
        public Nullable<int> r62 { get; set; }
        public Nullable<int> r63 { get; set; }
        public Nullable<int> r64 { get; set; }
        public Nullable<int> r65 { get; set; }
        public Nullable<int> r66 { get; set; }
        public Nullable<int> r67 { get; set; }
        public Nullable<int> r68 { get; set; }
        public Nullable<int> r69 { get; set; }
        public Nullable<int> r70 { get; set; }
        public Nullable<int> r71 { get; set; }
        public Nullable<int> r72 { get; set; }
        public Nullable<int> r73 { get; set; }
        public Nullable<int> r74 { get; set; }
        public Nullable<int> r75 { get; set; }
        public Nullable<int> r76 { get; set; }
        public Nullable<int> r77 { get; set; }
        public Nullable<int> r78 { get; set; }
        public Nullable<int> r79 { get; set; }
        public Nullable<int> r80 { get; set; }
        public Nullable<int> r81 { get; set; }
        public Nullable<int> r82 { get; set; }
        public Nullable<int> r83 { get; set; }
        public Nullable<int> r84 { get; set; }
        public Nullable<int> r85 { get; set; }
    }
}
