//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageCapacitorTextIndicator
    {
        public int Workplace_CapacitorTextIndicatorKey { get; set; }
        public Nullable<int> CompetencyKey { get; set; }
        public string Source { get; set; }
        public string EnglishCompetencyName { get; set; }
        public string EnglishIndicator { get; set; }
        public string SpanishCompetencyName { get; set; }
        public string SpanishIndicator { get; set; }
        public string GermanCompetencyName { get; set; }
        public string GermanIndicator { get; set; }
        public string ChineseCompetencyName { get; set; }
        public string ChineseIndicator { get; set; }
        public string PortugueseCompetencyName { get; set; }
        public string PortugueseIndicator { get; set; }
    }
}
