//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageConsultant
    {
        public int LanguageConsultantKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string DevelopedBy { get; set; }
        public string Introduction { get; set; }
        public string Note { get; set; }
        public string NoteText { get; set; }
        public string Pure { get; set; }
        public string Situational { get; set; }
        public string Polarized { get; set; }
        public string EvidenceBias { get; set; }
        public string EvidenceBiasLegend { get; set; }
        public string ItemResponses { get; set; }
    }
}
