//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageNarratorNoResearch
    {
        public int NoResearchKey { get; set; }
        public int LanguageKey { get; set; }
        public string Section { get; set; }
        public string Trait { get; set; }
        public short WeightLevel { get; set; }
        public string Description { get; set; }
    }
}
