//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageCapacitorReport
    {
        public int LanguageCapacitorCompReportKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string ReportHeader { get; set; }
        public string EstimatedFit { get; set; }
        public string InterpretationOfFit { get; set; }
        public string FitLegend { get; set; }
        public string OptimumHeader { get; set; }
        public string ActualHeader { get; set; }
        public string AvailableHeader { get; set; }
        public string DescriptionHeader { get; set; }
        public string IndicatorPrefix { get; set; }
        public string SourceText { get; set; }
    }
}
