//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageConsultantResponseBias
    {
        public int LangaugeResponseBiasKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public Nullable<int> ResponseBias { get; set; }
        public string ResponseBiasText { get; set; }
    }
}
