//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageTraitTOC
    {
        public int LanguageTraitTOCKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string CustomReport { get; set; }
        public string DateString { get; set; }
        public string DateFormat { get; set; }
        public string TOC { get; set; }
        public string ReportTitle { get; set; }
        public string ReportSubtitle { get; set; }
        public string N { get; set; }
        public string E { get; set; }
        public string O { get; set; }
        public string A { get; set; }
        public string C { get; set; }
        public string Composite { get; set; }
        public string Page { get; set; }
        public string Rights { get; set; }
        public string NormGroup { get; set; }
        public string US { get; set; }
        public string Global { get; set; }
        public string Mexican { get; set; }
        public string German { get; set; }
        public string Portuguese { get; set; }
        public string Brazilian { get; set; }
        public string Chinese { get; set; }
        public string Singapore { get; set; }
    }
}
