//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkplace_LanguageConsultantTraitReport
    {
        public int ConsultantTraitReportKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string ReportHeader { get; set; }
        public string CompetencyHeader { get; set; }
        public string ShapeHeader { get; set; }
        public string LevelHeader { get; set; }
        public string DispersionHeader { get; set; }
        public string CoverageHeader { get; set; }
        public string FitHeader { get; set; }
        public string InterpretationHeader { get; set; }
        public string HROStrategy { get; set; }
        public string HighPerfHeader { get; set; }
        public string LowPerfHeader { get; set; }
        public string Continued { get; set; }
        public string Note { get; set; }
        public string NoteText { get; set; }
        public string InterpretaionGuide { get; set; }
        public string OverallFitLegend { get; set; }
        public string StrategyLegend { get; set; }
        public string PerformingWellText { get; set; }
        public string NotPerformingWellText { get; set; }
    }
}
