//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMaster360_ProjectSearch
    {
        public int ProjectKey { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CompletedCount { get; set; }
        public Nullable<int> SentCount { get; set; }
        public string ConsultantFName { get; set; }
        public string ConsultantLName { get; set; }
        public Nullable<int> OrganizationKey { get; set; }
        public Nullable<int> UserKey { get; set; }
        public Nullable<int> ProductKey { get; set; }
        public System.DateTime WP360ResponseDate { get; set; }
        public Nullable<int> WP360CompletedCount_Rater { get; set; }
        public Nullable<int> WP360CompletedCount_Assessee { get; set; }
        public Nullable<int> WP360SentCount_Rater { get; set; }
        public Nullable<int> WP360SentCount_Assessee { get; set; }
        public Nullable<int> WP360StartedCount { get; set; }
    }
}
