//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMaster_Project
    {
        public int ProjectKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string OrganizationName { get; set; }
        public string ConsultantFName { get; set; }
        public string ConsultantLName { get; set; }
        public string ConsultantName { get; set; }
        public string ConsultantEmail { get; set; }
        public string ProjectName { get; set; }
        public string ProductName { get; set; }
        public string QuestionnaireTypeName { get; set; }
        public string QuestionnaireTypeCode { get; set; }
        public string QuestionaireDelivery { get; set; }
        public string ReportDelivery { get; set; }
        public Nullable<int> OrganizationKey { get; set; }
        public Nullable<int> UserKey { get; set; }
        public Nullable<int> ProjectTypeKey { get; set; }
        public Nullable<int> ProductKey { get; set; }
        public Nullable<int> QuestionnaireTypeKey { get; set; }
        public Nullable<int> Questionnaire_LanguageKey_Default { get; set; }
        public Nullable<int> Report_LanguageKey_Default { get; set; }
        public Nullable<int> NormGroupKey_Default { get; set; }
        public Nullable<int> CompetencyTypeKey { get; set; }
        public Nullable<int> CompetencyGroupKey { get; set; }
        public Nullable<int> QuestionnaireDeliveryMethodKey { get; set; }
        public Nullable<int> ReportDeliveryMethodKey { get; set; }
        public string ShipPickupText { get; set; }
        public Nullable<System.DateTime> ShipPickupDate { get; set; }
        public Nullable<bool> TraitNarratorReport { get; set; }
        public Nullable<bool> TraitCapacitorReport { get; set; }
        public Nullable<bool> ConsultantReport { get; set; }
        public Nullable<bool> CareerGuider { get; set; }
        public Nullable<int> Teamer { get; set; }
        public Nullable<int> Leader { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> SentCount { get; set; }
        public Nullable<int> CompletedCount { get; set; }
        public string EmailQuestionnaireSubject { get; set; }
        public string EmailQuestionnaireText1 { get; set; }
        public string EmailQuestionnaireText2 { get; set; }
        public string EmailQuestionnaireText3 { get; set; }
        public string EmailReportSubject { get; set; }
        public string EmailReportText1 { get; set; }
        public string EmailReportText3 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TeamerReportName { get; set; }
        public string TeamerTeamName { get; set; }
        public string TeamerModuleKeys { get; set; }
        public string LeaderReportName { get; set; }
        public string LeaderModuleKeys { get; set; }
        public Nullable<bool> IsWebservice { get; set; }
        public Nullable<bool> IsWebserviceComplete { get; set; }
        public Nullable<int> CompanyKey { get; set; }
        public Nullable<System.DateTime> DateQuestionnaireSent { get; set; }
        public Nullable<bool> IsQuestionnaireSent { get; set; }
        public string ProductID { get; set; }
        public string WebserviceEventID { get; set; }
        public string ProjectTypeName { get; set; }
        public Nullable<bool> Learner { get; set; }
        public Nullable<int> OldProjectID { get; set; }
        public string ReportGUID { get; set; }
        public string TeamerReportFilename { get; set; }
        public Nullable<bool> ShortTraitReport { get; set; }
        public bool Standard360 { get; set; }
        public System.DateTime WP360ResponseDate { get; set; }
        public int NumberOfAssessees { get; set; }
        public Nullable<int> WP360SentCount { get; set; }
        public Nullable<int> WP360CompletedCount { get; set; }
        public Nullable<int> WP360CompletedCount_Rater { get; set; }
        public Nullable<int> WP360CompletedCount_Assessee { get; set; }
        public Nullable<int> WP360SentCount_Rater { get; set; }
        public Nullable<int> WP360SentCount_Assessee { get; set; }
        public bool IncludeCGQuestions { get; set; }
        public bool ValuesReport { get; set; }
        public int ResearchSet { get; set; }
    }
}
