//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMaster_Questionnaire
    {
        public int ProjectKey { get; set; }
        public int QuestionnaireKey { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Questionnaire_LanguageKey { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<bool> CareerGuiderIncluded { get; set; }
        public Nullable<bool> DemographicsIncluded { get; set; }
        public Nullable<bool> IsStarted { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsCareerGuiderStarted { get; set; }
        public Nullable<int> OrganizationKey { get; set; }
        public string QuestionnaireLanguage { get; set; }
        public string ReportLanguage { get; set; }
        public string NormGroup { get; set; }
        public string TypeCode { get; set; }
        public Nullable<bool> IsCareerGuiderCompleted { get; set; }
        public string TraitReportName { get; set; }
        public string NarratorReportName { get; set; }
        public string ConsultantReportName { get; set; }
        public string CapacitorReportName { get; set; }
        public string TraitNarratorReportName { get; set; }
        public Nullable<int> OldQuestionnaireID { get; set; }
        public Nullable<bool> Teamer { get; set; }
        public Nullable<bool> Leader { get; set; }
        public Nullable<bool> Learner { get; set; }
        public string ValuesReportName { get; set; }
    }
}
