//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMaster_Assessees
    {
        public Nullable<int> ProjectKey { get; set; }
        public Nullable<int> QuestionnaireKey { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsStarted { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsCareerGuiderStarted { get; set; }
        public Nullable<bool> IsCareerGuiderCompleted { get; set; }
        public Nullable<bool> IsQuestionnaireSent { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateCareerGuiderStarted { get; set; }
        public Nullable<System.DateTime> DateCareerGuiderCompleted { get; set; }
        public Nullable<System.DateTime> DateQuestionnaireSent { get; set; }
        public Nullable<System.DateTime> DateLastQuestionnaireSent { get; set; }
        public string BirthDate { get; set; }
        public string WebserviceTrackingKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> OldQuestionnaireID { get; set; }
        public int ResearchSet { get; set; }
    }
}
