//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrderInvoice
    {
        public int CompanyKey { get; set; }
        public string CompanyName { get; set; }
        public int OrganizationKey { get; set; }
        public string OrgName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderKey { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
