//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrdersFilter
    {
        public int OrderKey { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int UserKey { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxRate { get; set; }
        public decimal ShippingCost { get; set; }
        public decimal Discount { get; set; }
        public decimal Total { get; set; }
        public string ShipCompany { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipZipCode { get; set; }
        public string ShipCountry { get; set; }
        public string BillCompany { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillZipCode { get; set; }
        public string BillCountry { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string AuthCode { get; set; }
        public string PNREF { get; set; }
        public bool Complete { get; set; }
        public bool Removed { get; set; }
        public int PaymentType { get; set; }
        public string Comments { get; set; }
        public short BillingKey { get; set; }
        public string PONumber { get; set; }
        public short ShippingKey { get; set; }
        public string ShippingMethod { get; set; }
        public string TotalWeight { get; set; }
        public System.DateTime CompleteDate { get; set; }
        public bool Invoiced { get; set; }
    }
}
