//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSchoolplace_LanguageTrait
    {
        public int LanguageTraitDetailKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string TraitCode { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DetailTitle { get; set; }
        public string DetailDescription { get; set; }
    }
}
