//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSchoolplaceExport
    {
        public int QuestionnaireKey { get; set; }
        public string OrganizationName { get; set; }
        public string ConsultantFName { get; set; }
        public string ConsultantLName { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public string ProductName { get; set; }
        public string QuestionLanguage { get; set; }
        public string ReportLanguage { get; set; }
        public string DeliveryMethod { get; set; }
        public Nullable<System.DateTime> DateQuestionnaireSent { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<int> ProductKey { get; set; }
        public int Project_Questionnaire_Key { get; set; }
        public Nullable<int> UserKey { get; set; }
        public Nullable<int> OrganizationKey { get; set; }
    }
}
