//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentACS.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWorkplace_TeamerParticipants
    {
        public int Project_Questionnaire_Key { get; set; }
        public Nullable<int> ProjectKey { get; set; }
        public Nullable<bool> Teamer { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    }
}
